package hotel_reservation.views;


// NOTE : BILLING FUNCTION GIVING WRONG PRICING VALUE !!!!!!!!! IMPORTANT

import hotel_reservation.controllers.CheckIn_Controller;
import hotel_reservation.controllers.CheckOut_Controller;
import hotel_reservation.controllers.Reservation_Controller;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

import java.sql.*;
import net.proteanit.sql.DbUtils;

//EXPERIMENT 3.3

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class Reservation_View extends javax.swing.JFrame {

    /**
     * Creates new form Reservation_View
     */
    private Connection conn;// = null;
    private ResultSet rs;// = null;
    //PreparedStatement pst = null;
     private  PreparedStatement st;
     
      private Reservation_Controller rchecks;
      private  CheckIn_Controller checkin;
      private CheckOut_Controller checkout;
      public String v;
    public Reservation_View() {
        initComponents();
        setTitle("Hotel Reservation System");
        try {
          Class.forName("com.mysql.jdbc.Driver");
        conn =  DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");//javaconnect.ConnectDB();
        //st = conn.createStatement();
        
        
        checkin = new CheckIn_Controller();
        checkout = new CheckOut_Controller();
        rchecks = new Reservation_Controller();
        //Timestamp timestamp = new Timestamp(System.currentTimeMillis());
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                String text = dateFormat.format(getTimeStamp());
                this.v = text;
        
        CheckinDate.setText(text);
        CheckoutDate.setText(text);
        Update_table();
        } catch (Exception e) {
             System.out.println("Error: "+e);
        }
        
        
        
        
    }
    public void Update_table()
    {   try {
           String sql = "SELECT CONCAT(FirstName ,' ', LastName) as 'Guest',`RoomNumber` as 'Room',`CreditCardNumber`as 'Card Number',`Contact`,`Email`,`CheckInDate`as 'Check In Date'  FROM `guest` where `CheckOutDate` = '0000-00-00 00:00:00'";
        st = conn.prepareStatement(sql); 
        rs = st.executeQuery();
        Table_CurrentGuess.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e+"\n Error in this function Update_table()");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        textArea1 = new java.awt.TextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        fnamelabel = new javax.swing.JLabel();
        FnameField = new javax.swing.JTextField();
        lnamelabel = new javax.swing.JLabel();
        LnameField = new javax.swing.JTextField();
        addresslabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        PhoneField = new javax.swing.JTextField();
        roomnumberlabel = new javax.swing.JLabel();
        CheckinDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RoomNumberField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        CreditCardType = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CreditCardNumber = new javax.swing.JTextField();
        AddressField = new java.awt.TextField();
        ViewLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        CheckinButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        viewfield = new java.awt.TextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        RoomCheckOutLabel = new javax.swing.JLabel();
        ChekoutRoomTextField = new javax.swing.JTextField();
        CheckoutDate = new javax.swing.JTextField();
        ChekoutdateLabel = new javax.swing.JLabel();
        ExtraChargeLabel = new javax.swing.JLabel();
        ExtraCharge = new javax.swing.JTextField();
        CheckoutCreditNumberLabel = new javax.swing.JLabel();
        CheckoutCreditCardTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Extrainfo = new javax.swing.JTextField();
        ViewLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        ChekoutRoomNumber = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        BillingField = new java.awt.TextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_CurrentGuess = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        SearchTextField = new javax.swing.JTextField();
        ComboSearchBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        event = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        usagemenu = new javax.swing.JMenuItem();
        aboutmenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Guest Check In"));

        fnamelabel.setText("First Name");

        FnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameFieldActionPerformed(evt);
            }
        });

        lnamelabel.setText("   Last Name");

        LnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameFieldActionPerformed(evt);
            }
        });

        addresslabel.setText("   Address");

        phonelabel.setText("  Phone");

        roomnumberlabel.setText("Room No.");

        CheckinDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckinDateActionPerformed(evt);
            }
        });

        jLabel7.setText(" Check In Date");

        jLabel9.setText("Email");

        jLabel16.setText("Credit Card Type");

        jLabel17.setText("Credit Card No.");

        CreditCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditCardNumberActionPerformed(evt);
            }
        });

        AddressField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(fnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(57, 57, 57))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CheckinDate))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CreditCardType, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(roomnumberlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RoomNumberField)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(CreditCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phonelabel)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LnameField)
                            .addComponent(PhoneField))))
                .addGap(38, 38, 38))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(phonelabel)
                        .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomnumberlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CreditCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(CreditCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CheckinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        ViewLabel.setText("Rooms Available");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CheckinButton.setText("Submit");
        CheckinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(CheckinButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(CheckinButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton1.setText("Query Rooms");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(viewfield, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(170, 170, 170)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ViewLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ViewLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewfield, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Check In", jPanel2);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Guest Check Out"));

        RoomCheckOutLabel.setText("Room No.");

        ChekoutRoomTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChekoutRoomTextFieldActionPerformed(evt);
            }
        });

        CheckoutDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutDateActionPerformed(evt);
            }
        });

        ChekoutdateLabel.setText("Check Out Date");

        ExtraChargeLabel.setText("Extra Charges");

        ExtraCharge.setText("0.00");
        ExtraCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraChargeActionPerformed(evt);
            }
        });

        CheckoutCreditNumberLabel.setText("Credit Card No.");

        jLabel2.setText("Charge Description");

        Extrainfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtrainfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(RoomCheckOutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ChekoutdateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(CheckoutCreditNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(ExtraChargeLabel)
                        .addComponent(jLabel2)))
                .addGap(13, 13, 13)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CheckoutCreditCardTextField)
                        .addComponent(CheckoutDate)
                        .addComponent(ExtraCharge, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(Extrainfo))
                    .addComponent(ChekoutRoomTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomCheckOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChekoutRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckoutCreditNumberLabel)
                    .addComponent(CheckoutCreditCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChekoutdateLabel)
                    .addComponent(CheckoutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExtraChargeLabel)
                    .addComponent(ExtraCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Extrainfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        ViewLabel1.setText("Billing Information");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ChekoutRoomNumber.setText("Submit");
        ChekoutRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChekoutRoomNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(ChekoutRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(ChekoutRoomNumber))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        BillingField.setEditable(false);
        scrollPane1.add(BillingField);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(ViewLabel1))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(156, 156, 156)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(ViewLabel1)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(32, 32, 32)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 900, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Check Out", jPanel3);

        Table_CurrentGuess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_CurrentGuess);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));

        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        ComboSearchBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Room Number", "Credit Card Number", "Last Name", "Check In Date" }));
        ComboSearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSearchBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Search By");

        SearchButton.setText("Submit");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchButton)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SearchTextField)
                        .addComponent(ComboSearchBox, 0, 132, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(SearchButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display Current Guests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));

        jButton5.setText("Show All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton5)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jButton6)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(535, 535, 535)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Current Guests", jPanel1);

        jMenu1.setText("File");

        event.setText("Exit");
        event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventActionPerformed(evt);
            }
        });
        jMenu1.add(event);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        usagemenu.setText("Usage");
        usagemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usagemenuActionPerformed(evt);
            }
        });
        jMenu2.add(usagemenu);

        aboutmenu.setText("About");
        aboutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutmenuActionPerformed(evt);
            }
        });
        jMenu2.add(aboutmenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Manager Privileges");

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 905, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        viewfield.setEditable(false);
        viewfield.setText(checkin.ListAvailableRooms());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CheckinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckinButtonActionPerformed
        CheckInSubmit();
        
    }

    void CheckInSubmit() throws HeadlessException { 
        // TODO add your handling code here:
        
        try
        {
            String fname = FnameField.getText();
            String lname = LnameField.getText();
            String address = AddressField.getText();
            String phone = PhoneField.getText();
            String email = EmailField.getText();
            int roomnumber =Integer.parseInt(RoomNumberField.getText());
            String checkindate = CheckinDate.getText();
            String creditNumber = CreditCardNumber.getText();
            String creditType = CreditCardType.getText();
            int check = rchecks.roomcheck(roomnumber);
            if (check==-1 )
            {
                JOptionPane.showMessageDialog(null, "No such Room");
                return;
            }else
                if(fname.isEmpty()==false && lname.isEmpty()==false  && address.isEmpty()==false && phone.isEmpty()==false && check>0 && checkindate.isEmpty()==false  && creditNumber.isEmpty()==false  && creditType.isEmpty()==false )
                {
                    //check >0 means we got back a value from the database
                    System.out.println(" Hmm why");
                    if (check==roomnumber)
                    {
                        JOptionPane.showMessageDialog(null, "Room  "+roomnumber+" is already occupied");
                        return;
                    }
                    else
                        
                        // else*/
                        if (checkin != null){
                            checkin.addClient(fname,lname, phone,email,address,checkindate,roomnumber,creditType,Integer.parseInt(CreditCardNumber.getText()));
                            //connect.addData(ReservationID, name, address, phone, email, roomtype, roomnumber, checkindate, other);
                            clear();
                            Update_table();
                      
               fnamelabel.setForeground(Color.BLACK);
                lnamelabel.setForeground(Color.BLACK);
                 addresslabel.setForeground(Color.BLACK);
                phonelabel.setForeground(Color.BLACK);
                 roomnumberlabel.setForeground(Color.BLACK);
                jLabel7.setForeground(Color.BLACK);
                 jLabel17.setForeground(Color.BLACK);
                 jLabel16.setForeground(Color.BLACK);
                        }
                        else
                            System.out.println("Connect is null");
                }else {if(FnameField.getText().isEmpty())
                    fnamelabel.setForeground(Color.RED);
                else fnamelabel.setForeground(Color.BLACK);
                if(LnameField.getText().isEmpty())lnamelabel.setForeground(Color.RED);
                else lnamelabel.setForeground(Color.BLACK);
                if(AddressField.getText().isEmpty() )addresslabel.setForeground(Color.RED);
                else addresslabel.setForeground(Color.BLACK);
                if(PhoneField.getText().isEmpty())phonelabel.setForeground(Color.RED);
                else phonelabel.setForeground(Color.BLACK);
                if(RoomNumberField.getText().isEmpty() )roomnumberlabel.setForeground(Color.RED);
                else roomnumberlabel.setForeground(Color.BLACK);
                if(CheckinDate.getText().isEmpty() )jLabel7.setForeground(Color.RED);
                else jLabel7.setForeground(Color.BLACK);
                if(CreditCardNumber.getText().isEmpty() )jLabel17.setForeground(Color.RED);
                else jLabel17.setForeground(Color.BLACK);
                if(CreditCardType.getText().isEmpty() )jLabel16.setForeground(Color.RED);
                else jLabel16.setForeground(Color.BLACK);
                JOptionPane.showMessageDialog(null, "Please enter required fields");
                }
            
        } 
        catch (Exception e) {
            
            
            
            if(FnameField.getText().isEmpty())
                fnamelabel.setForeground(Color.RED);
            else fnamelabel.setForeground(Color.BLACK);
            if(LnameField.getText().isEmpty())lnamelabel.setForeground(Color.RED);
            else lnamelabel.setForeground(Color.BLACK);
            if(AddressField.getText().isEmpty() )addresslabel.setForeground(Color.RED);
            else addresslabel.setForeground(Color.BLACK);
            if(PhoneField.getText().isEmpty())phonelabel.setForeground(Color.RED);
            else phonelabel.setForeground(Color.BLACK);
            if(RoomNumberField.getText().isEmpty() )roomnumberlabel.setForeground(Color.RED);
            else roomnumberlabel.setForeground(Color.BLACK);
            if(CheckinDate.getText().isEmpty() )jLabel7.setForeground(Color.RED);
            else jLabel7.setForeground(Color.BLACK);
            if(CreditCardNumber.getText().isEmpty() )jLabel17.setForeground(Color.RED);
            else jLabel17.setForeground(Color.BLACK);
            if(CreditCardType.getText().isEmpty() )jLabel16.setForeground(Color.RED);
            else jLabel16.setForeground(Color.BLACK);
            
            if(RoomNumberField.getText().isEmpty()==false){JOptionPane.showMessageDialog(null, "Invalid Room /card Entry");roomnumberlabel.setForeground(Color.RED);}
            else roomnumberlabel.setForeground(Color.BLACK);
                
             if(  CreditCardNumber.getText().isEmpty()==false){JOptionPane.showMessageDialog(null, "Invalid Room/card  Entry");jLabel17.setForeground(Color.RED);}

            else jLabel17.setForeground(Color.BLACK); 
             JOptionPane.showMessageDialog(null, "Please enter CORRECT information into required fields");
            System.out.println(e);
            
        }
        
    }//GEN-LAST:event_CheckinButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CreditCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditCardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditCardNumberActionPerformed

    private void CheckinDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckinDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckinDateActionPerformed

    private void LnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameFieldActionPerformed

    private void FnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameFieldActionPerformed

    private void AddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFieldActionPerformed

    private void ChekoutRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChekoutRoomNumberActionPerformed
        CheckOutSubmit();  
                

    }

    void CheckOutSubmit() throws HeadlessException {
        try {
            int roomnumber =Integer.parseInt(ChekoutRoomTextField.getText());
            int check =rchecks.roomcheck(roomnumber);
            
            System.out.println("Apple 1 Check: "+check);
            if (check==roomnumber )
            {
                JOptionPane.showMessageDialog(null, "Successful");
                RoomCheckOutLabel.setForeground(Color.BLACK);
            }
            if (check==-1 )
            {
                JOptionPane.showMessageDialog(null, "No such Room");
                RoomCheckOutLabel.setForeground(Color.RED);
            }
            if (check==1 )
            {
                JOptionPane.showMessageDialog(null, "No Check in information was found\nto be associated with room: "+roomnumber);
                RoomCheckOutLabel.setForeground(Color.RED);
                //return;
            }
        } catch (Exception e) {
            // if(ChekoutRoomTextField.getText().isEmpty())RoomCheckOutLabel.setForeground(Color.RED);
            //  else {
            //   if(ChekoutRoomTextField.getText().isEmpty()==false)
            JOptionPane.showMessageDialog(null, "Invalid room entry");
            RoomCheckOutLabel.setForeground(Color.RED);
            //}
        }try {
            int creditcard = Integer.parseInt(CheckoutCreditCardTextField.getText());
            int roomnumber =Integer.parseInt(ChekoutRoomTextField.getText());
            int check2 = rchecks.CardCheck(creditcard,roomnumber);
            
            if (check2==creditcard )
            {
                CheckoutCreditNumberLabel.setForeground(Color.BLACK);
            }
            else{
                CheckoutCreditNumberLabel.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Previous credit number required");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid credit entry");
            CheckoutCreditNumberLabel.setForeground(Color.RED);
        }try {
            Double extra = Double.parseDouble( ExtraCharge.getText());
            if(extra<0 ){
                JOptionPane.showMessageDialog(null, "Invalid Charge entry");
                ExtraCharge.setText("0.00");
                ExtraChargeLabel.setForeground(Color.BLACK);
            }
            
            
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Invalid Charge entry");
            ExtraCharge.setText("0.00");
            ExtraChargeLabel.setForeground(Color.BLACK);
        }try {
            String checkoutdate = CheckoutDate.getText();
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            if( checkoutdate.isEmpty()){
                JOptionPane.showMessageDialog(null, "Invalid  check out date");
                CheckoutDate.setText(dateFormat.format(getTimeStamp()));
                
            }
        } catch (Exception e) {
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            
            JOptionPane.showMessageDialog(null, "Invalid  check out date");
            CheckoutDate.setText(dateFormat.format(getTimeStamp()));
            
        }
        try {
            int roomnumber =Integer.parseInt(ChekoutRoomTextField.getText());
            int check = rchecks.roomcheck(roomnumber); 
            int creditcard = Integer.parseInt(CheckoutCreditCardTextField.getText());
            int check2 = rchecks.CardCheck(creditcard,roomnumber);
            String checkoutdate = CheckoutDate.getText();
            String extrainfo= Extrainfo.getText();
            Double extra = Double.parseDouble( ExtraCharge.getText());
            if (checkin != null){
                if(roomnumber==check && creditcard ==check2 && checkoutdate.isEmpty()==false && extra>=0.00){
                    
                    BillingField.setText( checkout.bill(roomnumber,creditcard,checkoutdate,extra,extrainfo));
                    ChekoutRoomTextField.setText("");
                    CheckoutCreditCardTextField.setText("");
                    ExtraCharge.setText("0.00");
                    //BillingField.setText("");
                    Extrainfo.setText("");
                    Update_table();
                     viewfield.setText(checkin.ListAvailableRooms());
                }
            }
            else
            {
                System.out.println("Connect is null");
            } 
        } catch (Exception e) {
        }
                

    }//GEN-LAST:event_ChekoutRoomNumberActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
         clear2();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CheckoutDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckoutDateActionPerformed

    private void ChekoutRoomTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChekoutRoomTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ChekoutRoomTextFieldActionPerformed

    private void ExtraChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraChargeActionPerformed

    private void ExtrainfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtrainfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtrainfoActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void ComboSearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSearchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSearchBoxActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        GuestSearch();
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         Update_table();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         Update_table();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventActionPerformed
        // TODO add your handling code here:
        String command = event.getActionCommand();
		//setStatus(command + " menu selected.");

		if (command.equals("Exit"))
			System.exit(0);
    }//GEN-LAST:event_eventActionPerformed

    private void usagemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usagemenuActionPerformed
   
        String command = usagemenu.getActionCommand();
        if(command.equals("Usage"))
			JOptionPane.showMessageDialog(null,"Hotel Reservation System ,Manage information on Clients and Hotel Rooms along with billing information.\nEnter data in relevant fields to perform functions.\nData in irrelevant fields will be ignored.\nSee User's Guide for more details.");
    }//GEN-LAST:event_usagemenuActionPerformed

    private void aboutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutmenuActionPerformed
        
        String command = aboutmenu.getActionCommand();
        if(command.equals("About")) JOptionPane.showMessageDialog(null,"About Hotel Reservation System, COMP 3250: Software Engineering.\nAuthor: David Charles (c) 2014");
    }//GEN-LAST:event_aboutmenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Manager_login_view regFace =new Manager_login_view();
                regFace.setVisible(true);
                dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void clear() {
		FnameField.setText("");
		AddressField.setText("");
		PhoneField.setText("");
		LnameField.setText("");
                EmailField.setText("");
                RoomNumberField.setText("");
                viewfield.setText("");
                CreditCardNumber.setText("");
                CreditCardType.setText("");
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                String text = dateFormat.format(getTimeStamp());
        
                 CheckinDate.setText(text);
	}
    private void clear2() {
		ChekoutRoomTextField.setText("");
		CheckoutCreditCardTextField.setText("");
		ExtraCharge.setText("0.00");
                BillingField.setText("");
		Extrainfo.setText("");
	}
    private static Timestamp getTimeStamp() {
        return new Timestamp(new Date().getTime());
    }
    
    private void GuestSearch()
    {
       String item = ComboSearchBox.getSelectedItem().toString();
       if(item.equals("Last Name")){
           try {
               String LastName = SearchTextField.getText();
       String sql = "SELECT CONCAT(FirstName ,' ', LastName) as 'Guest',`RoomNumber` as 'Room',`CreditCardNumber`as 'Card Number',`Contact`,`Email`,`CheckInDate`as 'Check In Date' FROM `guest` where `CheckOutDate` = '0000-00-00 00:00:00'and `LastName`='"+LastName+"'";
        st = conn.prepareStatement(sql); 
        rs = st.executeQuery();
        Table_CurrentGuess.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
           
       
       }
       if(item.equals("Credit Card Number")){
           try {
               String CardNumber = SearchTextField.getText();
       String sql = "SELECT CONCAT(FirstName ,' ', LastName) as 'Guest',`RoomNumber` as 'Room',`CreditCardNumber`as 'Card Number',`Contact`,`Email`,`CheckInDate`as 'Check In Date'  FROM `guest` where `CheckOutDate` = '0000-00-00 00:00:00'and `CreditCardNumber`='"+CardNumber+"'";
        st = conn.prepareStatement(sql); 
        rs = st.executeQuery();
        Table_CurrentGuess.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
       
       }
       if(item.equals("Room Number")){
            try {
               String Room = SearchTextField.getText();
       String sql = "SELECT CONCAT(FirstName ,' ', LastName) as 'Guest',`RoomNumber` as 'Room',`CreditCardNumber`as 'Card Number',`Contact`,`Email`,`CheckInDate`as 'Check In Date' FROM `guest` where `CheckOutDate` = '0000-00-00 00:00:00'and `RoomNumber`='"+Room+"'";
        st = conn.prepareStatement(sql); 
        rs = st.executeQuery();
        Table_CurrentGuess.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
       }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation_View().setVisible(true);
            }
            
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField AddressField;
    private java.awt.TextArea BillingField;
    private javax.swing.JButton CheckinButton;
    private javax.swing.JTextField CheckinDate;
    private javax.swing.JTextField CheckoutCreditCardTextField;
    private javax.swing.JLabel CheckoutCreditNumberLabel;
    private javax.swing.JTextField CheckoutDate;
    private javax.swing.JButton ChekoutRoomNumber;
    private javax.swing.JTextField ChekoutRoomTextField;
    private javax.swing.JLabel ChekoutdateLabel;
    private javax.swing.JComboBox ComboSearchBox;
    private javax.swing.JTextField CreditCardNumber;
    private javax.swing.JTextField CreditCardType;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField ExtraCharge;
    private javax.swing.JLabel ExtraChargeLabel;
    private javax.swing.JTextField Extrainfo;
    private javax.swing.JTextField FnameField;
    private javax.swing.JTextField LnameField;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JLabel RoomCheckOutLabel;
    private javax.swing.JTextField RoomNumberField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JTable Table_CurrentGuess;
    private javax.swing.JLabel ViewLabel;
    private javax.swing.JLabel ViewLabel1;
    private javax.swing.JMenuItem aboutmenu;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JMenuItem event;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lnamelabel;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JLabel roomnumberlabel;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.TextArea textArea1;
    private javax.swing.JMenuItem usagemenu;
    private java.awt.TextArea viewfield;
    // End of variables declaration//GEN-END:variables
}
